title: Il Dentista Senza Denti
baseurl: "/il-dentista-senza-denti"
url: "https://cialdecompatibili-netizen.github.io"
email: 
description: Sito comico dedicato alle disavventure di un dentista… senza denti.
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
exclude:
  - vendor

timezone:

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Dr. Sorriso Molle
  avatar: "/assets/images/bio-photo.jpg"
  bio: Ex dentista, ora comico per necessità. Specializzato in risate, non in masticazione.
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

permalink: /:categories/:title/
